apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cilcalator
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
spec:
  rules:
  - host: docker-staging-test.be
    http:
      paths:
      - backend:
          serviceName: test-cilcalator-master--web
          servicePort: 80
        path: /*
