apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-cilcalator
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: docker-staging-test.be
    http:
      paths:
      - backend:
          serviceName: test-cilcalator-master--web
          servicePort: 80
        path: /
