# Ruby CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/ruby/ for more details
#
version: 2.1


orbs:
  ruby: circleci/ruby@0.1.2 # Ruby orb registry: https://circleci.com/orbs/registry/orb/circleci/ruby
  aws-cli: circleci/aws-cli@0.1.13
  aws-ecr: circleci/aws-ecr@6.2.0
  aws-eks: circleci/aws-eks@0.2.1

jobs:
  build-stage: &build-stage
    docker:
      - image: circleci/ruby:2.1.10
    working_directory: ~/myapp
    steps:
      - checkout
      - setup_remote_docker
      - aws-ecr/build-image:
          repo: ${REPOSITORY_NAME}
          tag: "${CIRCLE_BRANCH}-${CIRCLE_SHA1}"
      - aws-cli/install
      - aws-ecr/ecr-login
      - aws-ecr/push-image:
          repo: ${REPOSITORY_NAME}
          tag: "${CIRCLE_BRANCH}-${CIRCLE_SHA1}"
  deploy-stage: &deploy-stage
    working_directory: ~/myapp
    executor: aws-eks/python3
    steps:
      - run:
          name: Add bin to path
          command: |
            echo 'export PATH=$PATH:~/.local/bin' >> $BASH_ENV
            echo 'export IMAGE_NAME=${AWS_ECR_ACCOUNT_URL}/${REPOSITORY_NAME}:${CIRCLE_BRANCH}-${CIRCLE_SHA1}'  >> $BASH_ENV
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: ${CLUSTER_NAME}
          aws-region: us-east-2
          install-kubectl: true
      - run:
          name: Set envars
          command: echo 'export APP_NAME=${REPOSITORY_NAME}-${CIRCLE_BRANCH}' >> $BASH_ENV
      - checkout
      - run:
          name: Deploy
          command: |
            sudo apt update
            sudo apt install -qq -y gettext
            envsubst < .k8s/templates/staging.yml > k8s.yml
            kubectl apply -f k8s.yml
            kubectl get pod
      # - run:
      #     name: Deploy to Kubernetes
      #     command: |
      #       sudo apt update
      #       sudo apt install -qq -y gettext
      #       envsubst < ${HOME}/myapp/.k8s/templates/staging.yml > ${HOME}/k8s.yml
      #       kubectl apply -f ${HOME}/k8s.yml
  ingress-stage: &ingress-stage
    docker:
      - image: opsmetricks/ingress-aws-cli
    environment:
      - PROJECT_NAME: cilcalator
    steps:
      - run:
          name: Set envars
          command: |
            echo 'export APP_NAME=${REPOSITORY_NAME}-${CIRCLE_BRANCH}' >> $BASH_ENV
      - run:
          name: Adding Ingress rule
          command: |
            aws eks --region us-east-2 update-kubeconfig --name cilcalator
            /ingress_rules_editor -ingress=cilcalator -service=${APP_NAME}--web -host=${APP_NAME}.docker-staging-test.be -port=80 -y add

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build-stage:
          context: cilcalator-stage
      - deploy-stage:
          context: cilcalator-stage
          requires:
          - build-stage

# What to do next? Set up a test job. Please see
# https://circleci.com/docs/2.0/configuration-reference/, for more  info on how to get started.
