# Ruby CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/ruby/ for more details
#
version: 2.1


orbs:
  ruby: circleci/ruby@0.1.2 # Ruby orb registry: https://circleci.com/orbs/registry/orb/circleci/ruby
  aws-cli: circleci/aws-cli@0.1.13
  aws-ecr: circleci/aws-ecr@6.2.0
  aws-eks: circleci/aws-eks@0.2.1

jobs:
  build-stage: &build-stage
    docker:
      - image: circleci/ruby:2.1.10
    working_directory: ~/myapp
    steps:
      - checkout
      - setup_remote_docker
      - aws-ecr/build-image:
          repo: ${REPOSITORY_NAME}
          tag: "${CIRCLE_BRANCH}-${CIRCLE_SHA1}"
      - aws-cli/install
      - aws-ecr/ecr-login
      - aws-ecr/push-image:
          repo: ${REPOSITORY_NAME}
          tag: "${CIRCLE_BRANCH}-${CIRCLE_SHA1}"
  deploy-stage: &deploy-stage
    working_directory: ~/myapp
    executor: aws-eks/python3
    steps:
      - run:
          name: Add bin to path
          command: |
            echo 'export PATH=$PATH:~/.local/bin' >> $BASH_ENV
            echo 'export IMAGE_NAME=${AWS_ECR_ACCOUNT_URL}/${REPOSITORY_NAME}:${CIRCLE_BRANCH}-${CIRCLE_SHA1}'  >> $BASH_ENV
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: ${CLUSTER_NAME}
          aws-region: us-east-2
          install-kubectl: true
      - run:
          name: Set envars
          command: echo 'export APP_NAME=${REPOSITORY_NAME}-${CIRCLE_BRANCH}' >> $BASH_ENV
      - checkout
      - run:
          name: Prepare K8S templates
          command: |
            aws eks --region ${AWS_DEFAULT_REGION} update-kubeconfig --name ${CLUSTER_NAME}
            rm -rf .k8s/.generated && mkdir -p .k8s/.generated
            for f in .k8s/templates/staging.yml
              do
              envsubst < $f > ".k8s/.generated/$(basename $f)"
            done
      - run:
          name: Deploy
          command: |
            kubectl apply -f .k8s/.generated/ --validate=true
      # - run:
      #     name: Deploy to Kubernetes
      #     command: |
      #       sudo apt update
      #       sudo apt install -qq -y gettext
      #       envsubst < ${HOME}/myapp/.k8s/templates/staging.yml > ${HOME}/k8s.yml
      #       kubectl apply -f ${HOME}/k8s.yml

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build-stage:
          context: cilcalator-stage
      - deploy-stage:
          context: cilcalator-stage
          requires:
          - build-stage

# What to do next? Set up a test job. Please see
# https://circleci.com/docs/2.0/configuration-reference/, for more  info on how to get started.
