apiVersion: v1
kind: ConfigMap
metadata:
  name: ${APP_NAME}--env
  labels:
    app: ${APP_NAME}
data:
  ENV_VALUE1: test

---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ${APP_NAME}--web
  labels:
    app: ${APP_NAME}
spec:
  replicas: ${CONTAINER_WEB_REPLICAS}
  selector:
    matchLabels:
      name: ${APP_NAME}--web-pod
  template:
    metadata:
      labels:
        name: ${APP_NAME}--web-pod
    spec:
      restartPolicy: Always
      containers:
      - name: ${APP_NAME}--web-container
        image: ${AWS_ECR_ACCOUNT_URL}/${REPOSITORY_NAME}:${CIRCLE_BRANCH}-${CIRCLE_SHA1}
        ports:
          - containerPort: 3000
            protocol: TCP
        envFrom:
          - configMapRef:
              name: ${APP_NAME}--env

---

kind: Service
apiVersion: v1
metadata:
  name: ${APP_NAME}--web
  labels:
    app: ${APP_NAME}
spec:
  selector:
    name: ${APP_NAME}--web-pod
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type : NodePort

---
